name: WGRegionInfo
main: net.aseom.mc.wgregioninfo.WGRegionInfo
version: 1.0
softdepend: [WorldGuard, WGRegionEvents]

commands:
  regioninfo:
    description: "RegionInfo command."
    usage: "Wrong command."
  regionhud:
    aliases: [rghud]
    description: "Toggle RegionInfo HUD."