name: WGRegionInfo
main: net.aseom.mc.wgregioninfo.WGRegionInfo
version: 0.1-alpha
softdepend: [WorldGuard, WGRegionEvents]

commands:
  regioninfo:
    aliases: [rginfo, rgi]
    description: "RegionInfo command."
    usage: "Wrong command."
  regionhud:
    aliases: [rghud, rgh]
    description: "Toggle RegionInfo HUD."