name: WGRegionInfo
main: net.aseom.mc.wgregioninfo.WGRegionInfo
version: 1.0
softdepend: [WorldGuard, WGRegionEvents]

commands:
  regioninfo:
    aliases: [rginfo, rgi]
    description: "RegionInfo command."
    usage: "Usage: '/rginfo enter-title, enter-subtitle, leave-title, leave-subtitle, newgroup, delgroup, addregion, delregion, reload'"
  regionhud:
    aliases: [rghud, rgh]
    description: "Toggle RegionInfo HUD."